# Generated by Django 5.2.3 on 2025-07-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminpanel", "0001_initial"),
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donor.donor",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminpanel.volunteer",
            ),
        ),
    ]
