# Generated by Django 5.2.2 on 2025-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='collect',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
