# Generated by Django 5.2.3 on 2025-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer_email", models.EmailField(max_length=254)),
                ("volunteer_name", models.CharField(max_length=100)),
                ("health_score", models.FloatField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "work_eligibility",
                    models.CharField(
                        choices=[
                            ("eligible", "Eligible"),
                            ("not_eligible", "Not Eligible"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("analysis_data", models.TextField(default="{}")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "health_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer_email", models.EmailField(max_length=254)),
                ("volunteer_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("heart_rate", models.IntegerField()),
                ("blood_pressure_systolic", models.IntegerField()),
                ("blood_pressure_diastolic", models.IntegerField()),
                ("oxygen_saturation", models.IntegerField()),
                ("respiratory_rate", models.IntegerField()),
                ("covid_symptoms", models.BooleanField(default=False)),
                (
                    "fatigue_level",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                (
                    "stress_level",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ]
                    ),
                ),
                ("sleep_hours", models.FloatField()),
                ("bmi", models.FloatField()),
                ("chronic_conditions", models.BooleanField(default=False)),
                (
                    "fitness_level",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "health_check",
                "ordering": ["-created_at"],
            },
        ),
    ]
