# Generated by Django 5.2.3 on 2025-07-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0002_healthanalysis_healthcheck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthanalysis",
            name="volunteer_email",
        ),
        migrations.RemoveField(
            model_name="healthcheck",
            name="volunteer_email",
        ),
        migrations.AddField(
            model_name="healthanalysis",
            name="volunteer_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="volunteer_id",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
