# Generated by Django 5.2.3 on 2025-07-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0003_remove_healthanalysis_volunteer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthcheck",
            name="volunteer_email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AlterModelTable(
            name="donorreport",
            table="donorreport",
        ),
    ]
