# Generated by Django 5.2.3 on 2025-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0004_update_donorreport_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="donorreport",
            name="volunteer_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the volunteer who created this report",
                max_length=100,
                null=True,
            ),
        ),
    ]
