# Generated by Django 5.2.3 on 2025-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteer", "0005_add_volunteer_name_to_donorreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volunteer_id",
                    models.IntegerField(help_text="ID of the volunteer being reported"),
                ),
                (
                    "volunteer_name",
                    models.CharField(
                        help_text="Name of the volunteer being reported", max_length=100
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the donor who created this report",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "volunteerreport",
            },
        ),
    ]
