# Generated by Django 5.2.3 on 2025-07-05 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donor", "0001_initial"),
        ("volunteer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donate",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="volunteer.volunteer",
            ),
        ),
        migrations.AddField(
            model_name="donate",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="donor.donor"
            ),
        ),
    ]
