# Generated by Django 5.2.3 on 2025-07-10 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="donate",
            table="donate",
        ),
    ]
