# Generated by Django 5.1.4 on 2025-05-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_created_at_alter_donor_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
    ]
