# Generated by Django 5.1.4 on 2025-05-07 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donor_created_at_alter_donor_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('food_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('storage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('packaging_type', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
