# Generated by Django 5.1.4 on 2025-05-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor'),
        ),
    ]
