# Generated by Django 5.2.2 on 2025-06-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_alter_donate_donor'),
        ('volunteer', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='accepted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='donate',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteer'),
        ),
    ]
